### ISSUE TITLE
PCB Layout or Measurements DXF

### ISSUE THREAD

**Issue by 32teeth** [hardkernel/ODROID-GO#16]
Hi, @hardkernel @leeseungcheol @awesometic 

As a hardware developer looking to create add on boards for the Odroid Go,
I kindly ask you to provide a PCB with outline or DXF with measurements

If at al possible, perhaps a Private GitHub Repo and add me as a member ;)

I'd be happy with an NDA if needed.

Thanks in advance
Look forward to you reply

**Comment by leeseungcheol** [comment]
Hi,

You can find the DXF with the measurements in our wiki.
https://wiki.odroid.com/odroid_go/odroid_go#documentations

**Comment by 32teeth** [comment]
Thanks @leeseungcheol
