### ISSUE TITLE
hello wold compile failure

### ISSUE THREAD

**Issue by techneo** [hardkernel/ODROID-GO#2]
I get the following error when compiling the Hello_World using Arduino IDE.

C:\Users\suren\Documents\Arduino\libraries\ODROID-GO\src\sensors\ir\IRremote.cpp: In function 'void IRTimer()':

C:\Users\suren\Documents\Arduino\libraries\ODROID-GO\src\sensors\ir\IRremote.cpp:196:24: error: statement has no effect [-Werror=unused-value]

     else BLINKLED_ON() ;   // if no user defined LED pin, turn default LED pin for the hardware on

**Comment by seungchar** [comment]
I don't understand why the error occurred when you compile the Hello_World.
The Hello_World example does not include the IR sensor library.

**Comment by seungchar** [comment]
And did you install Arduino IDE for ESP32?
https://wiki.odroid.com/odroid_go/arduino/01_arduino_setup#install_arduino_ide_for_esp32

**Comment by techneo** [comment]
yes. I am using other ESP32 modules without any issues. 

Error occurs when including the ODROID library

**Comment by techneo** [comment]
digging deeper I found 
#	define BLINKLED_ON()   1
for ESP32. 
So  code gets compiles as 
1; 

This warning is treated as a a error by the compiler., ( [-Werror=unused-value] )

Is there a workaround ?
